#! /bin/bash


. ./scripts/planetlab/pl-common.sh



# TOPOLOGY
DCS[0]=${EC2_PROD_EU_M1SMALL[0]}
DCSEQ[0]=${EC2_PROD_EU_M1SMALL[1]}

DCS[1]=${EC2_PROD_EU_M1SMALL[2]}
DCSEQ[1]=${EC2_PROD_EU_M1SMALL[3]}

DC_CLIENTS[0]=${EC2_PROD_EU_M1SMALL[4]}
DC_CLIENTS[1]=${EC2_PROD_EU_M1SMALL[5]}


MACHINES="${DCS[*]} ${DC_CLIENTS[*]}"
INIT_DB_DC=${DCS[0]}
INIT_DB_CLIENT=${EC2_PROD_EU_M1SMALL[0]}


# INPUT DATA PARAMS
INPUT_USERS=2500
INPUT_ACTIVE_USERS=10
INPUT_USER_FRIENDS=25
INPUT_USER_BIASED_OPS=9
INPUT_USER_RANDOM_OPS=1
INPUT_USER_OPS_GROUPS=500
FILE_USERS=input/users.txt
FILE_CMDS_PREFIX=input/commands.txt

# BENCHMARK PARAMS
NOTIFICATIONS=false
ISOLATION=REPEATABLE_READS
CACHING=STRICTLY_MOST_RECENT
CACHE_EVICTION_TIME_MS=120 #120000
ASYNC_COMMIT=false
THINK_TIME_MS=0
MAX_CONCURRENT_SESSIONS_PER_JVM=5

echo "==== STARTING SEQUENCERS AND DC SERVERS ===="

. ./scripts/planetlab/pl-start-servers-ds-seq.sh 

servers_start DCS DCSEQ
